# Generated by Django 5.1.1 on 2025-11-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_usergamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamescore',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergamescore',
            name='is_participated',
            field=models.BooleanField(default=False),
        ),
    ]
