# Generated by Django 5.1.1 on 2025-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
