# Generated by Django 5.1.1 on 2025-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_agenda_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
