# Generated by Django 5.1.1 on 2025-12-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_agenda_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamescore',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
