# Generated by Django 5.1.1 on 2025-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_usergamescore_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamescore',
            name='participated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
